---
title: "FreeBSD Code of Conduct"
sidenav: docs
--- 

= FreeBSD Code of Conduct

== FreeBSD Code of Conduct

The FreeBSD Project is inclusive. We want the FreeBSD Project to be a venue where people of all backgrounds can work together to make the best operating system, built by a strong community. These values extend beyond just development to all aspects of the Project. All those given recognition as members of the Project in whatever form are seen as ambassadors of the Project.

Diversity is a huge strength and is critical to the long term success of the Project. To that end we have a few ground rules that we ask people to adhere to. This code applies equally to everyone representing the FreeBSD Project in any way, from new members, to committers, to the core team itself. These rules are intended to ensure a safe, harassment-free environment for all and to ensure that everyone feels welcome both working within, and interacting with, the Project.

This document is not an exhaustive list of things that you should not do. Rather, consider it a guide to make it easier to enrich all of us and the technical communities in which we participate.

This code of conduct applies to all spaces used by the FreeBSD Project, including our mailing lists, IRC channels, and social media, both online and off. Anyone who is found to violate this code of conduct may be sanctioned or expelled from FreeBSD Project controlled spaces at the discretion of the FreeBSD Code of Conduct Committee.

Some FreeBSD Project spaces may have additional rules in place, which will be made clearly available to participants. Participants are responsible for knowing and abiding by these rules. Harassment includes but is not limited to:

* Comments that reinforce systemic oppression related to gender, gender identity and expression, sexual orientation, disability, mental illness, neurodiversity, physical appearance, body size, age, race, or religion.
* Unwelcome comments regarding a person's lifestyle choices and practices, including those related to food, health, parenting, drugs, and employment.
* Deliberate misgendering.
* Deliberate use of "dead" or rejected names.
* Gratuitous or off-topic sexual images or behaviour in spaces where they're not appropriate.
* Physical contact and simulated physical contact (e.g., textual descriptions like "*hug*" or "*backrub*") without consent or after a request to stop.
* Threats of violence.
* Incitement of violence towards any individual, including encouraging a person to commit suicide or to engage in self-harm.
* Deliberate intimidation.
* Stalking or following.
* Harassing photography or recording, including logging online activity for harassment purposes.
* Sustained disruption of discussion.
* Unwelcome sexual attention.
* Pattern of inappropriate social contact, such as requesting/assuming inappropriate levels of intimacy with others.
* Continued one-on-one communication after requests to cease.
* Deliberate "outing" of any private aspect of a person's identity without their consent except as necessary to protect vulnerable people from intentional abuse.
* Publication of non-harassing private communication without consent.
* Publication of non-harassing private communication with consent but in a way that intentionally misrepresents the communication (e.g., removes context that changes the meaning).
* Knowingly making harmful false claims about a person.

== Reporting

The reporting process is documented at link:../conduct-reporting[Code of Conduct Reporting Instructions].

== Glossary

Systemic oppression:

* The ways in which history, culture, ideology, public policies, institutional practices, and personal behaviors and beliefs interact to maintain a hierarchy - based on race, class, gender, sexuality, and/or other group identities - that allows the privileges associated with the dominant group and the disadvantages associated with the oppressed, targeted, or marginalized group to endure and adapt over time. (Derived from Aspen Institute, via Open Source Leadership)

Dead names:

* A name assigned to a person at birth which they no longer identify with. Most often used to refer to the assigned name of a trans person who has publicly identified themselves under a new name. Deliberately using a dead name is an act of hostility.

== Attribution

This Code of Conduct is based on the example policy from the http://geekfeminism.wikia.com/wiki/Community_anti-harassment[Geek Feminism wiki].
