---
title: FreeBSD Handbuch
authors:
  - author: The FreeBSD Documentation Project
copyright: 1995-2020 The FreeBSD Documentation Project
releaseinfo: "$FreeBSD: head/en_US.ISO8859-1/books/handbook/book.xml 54263 2020-06-16 15:54:02Z gjb $" 
trademarks: ["freebsd", "ibm", "ieee", "redhat", "3com", "adobe", "apple", "intel", "linux", "microsoft", "opengroup", "sun", "realnetworks", "oracle", "3ware", "arm", "adaptec", "google", "heidelberger", "intuit", "lsilogic", "themathworks", "thomson", "vmware", "wolframresearch", "xiph", "xfree86", "general"] 
next: books/handbook/preface
---

= FreeBSD Handbuch
:doctype: book
:toc: macro
:toclevels: 2
:icons: font
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnums:
:partnums:
:chapter-signifier: Chapter
:part-signifier: Part
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:figure-caption: Figure

include::share/releases.adoc[]
include::share/de/mailing-lists.adoc[lines=6..-1]

[.abstract-title]
Zusammenfassung

Willkommen bei FreeBSD! Dieses Handbuch beschreibt die Installation und den täglichen Umgang mit _FreeBSD {rel121-current}-RELEASE_, _FreeBSD {rel113-current}-RELEASE_. Das Handbuch ist das Ergebnis einer fortlaufenden Arbeit vieler Einzelpersonen. Dies kann dazu führen, dass einige Abschnitte nicht aktuell sind. Bei Unklarheiten empfiehlt es sich daher stets, die link:{handbook}[englische Originalversion] des Handbuchs zu lesen.

Wenn Sie bei der Übersetzung des Handbuchs mithelfen möchten, senden Sie bitte eine E-Mail an die Mailingliste {de-doc}.

Die aktuelle Version des Handbuchs ist immer auf dem https://www.FreeBSD.org/[FreeBSD-Webserver] verfügbar und kann in verschiedenen Formaten und in komprimierter Form vom https://download.freebsd.org/ftp/doc[FreeBSD FTP-Server] oder einem der vielen <<mirrors-ftp,Spiegel>> herunter geladen werden (ältere Versionen finden Sie hingegen unter https://docs.FreeBSD.org/doc/[https://docs.FreeBSD.org/doc/]). Gedruckte Kopien können bei https://www.freebsdmall.com/[FreeBSD Mall] erworben werden. Vielleicht möchten Sie das Handbuch oder andere Dokumente auch link:https://www.FreeBSD.org/search/[durchsuchen].

'''

include::content/en/books/handbook/toc.adoc[]
