title = "FreeBSD プロジェクト"
contentDir = "content/ja"
languageName = "Japanese"
weight = 3

[books]
dev-model = "ja_JP.eucJP/books/dev-model/"
faq = "ja_JP.eucJP/books/faq/"
handbook = "ja_JP.eucJP/books/handbook/"
developers-handbook = "ja_JP.eucJP/books/developers-handbook/"
arch-handbook = "ja_JP.eucJP/books/arch-handbook/"
porters-handbook = "ja_JP.eucJP/books/porters-handbook/"
design-44bsd = "ja_JP.eucJP/books/design-44bsd/"
fdp-primer = "ja_JP.eucJP/books/fdp-primer/"

[articles]
bsdl-gpl = "ja_JP.eucJP/articles/bsdl-gpl/"
building-products = "ja_JP.eucJP/articles/building-products/"
committers-guide = "ja_JP.eucJP/articles/committers-guide/"
contributing = "ja_JP.eucJP/articles/contributing/"
contributors = "ja_JP.eucJP/articles/contributors/"
cups = "ja_JP.eucJP/articles/cups/"
explaining-bsd = "ja_JP.eucJP/articles/explaining-bsd/"
filtering-bridges = "ja_JP.eucJP/articles/filtering-bridges/"
fonts = "ja_JP.eucJP/articles/fonts/"
freebsd-questions = "ja_JP.eucJP/articles/freebsd-questions/"
freebsd-update-server = "ja_JP.eucJP/articles/freebsd-update-server/"
geom-class = "ja_JP.eucJP/articles/geom-class/"
gjournal-desktop = "ja_JP.eucJP/articles/gjournal-desktop/"
hubs = "ja_JP.eucJP/articles/hubs/"
ipsec-must = "ja_JP.eucJP/articles/ipsec-must/"
ldap-auth = "ja_JP.eucJP/articles/ldap-auth/"
leap-seconds = "ja_JP.eucJP/articles/leap-seconds/"
linux-emulation = "ja_JP.eucJP/articles/linux-emulation/"
linux-users = "ja_JP.eucJP/articles/linux-users/"
mailing-list-faq = "ja_JP.eucJP/articles/mailing-list-faq/"
nanobsd = "ja_JP.eucJP/articles/nanobsd/"
new-users = "ja_JP.eucJP/articles/new-users/"
pam = "ja_JP.eucJP/articles/pam/"
pgpkeys = "ja_JP.eucJP/articles/pgpkeys/"
port-mentor-guidelines = "ja_JP.eucJP/articles/port-mentor-guidelines/"
pr-guidelines = "ja_JP.eucJP/articles/pr-guidelines/"
problem-reports = "ja_JP.eucJP/articles/problem-reports/"
rc-scripting = "ja_JP.eucJP/articles/rc-scripting/"
releng = "ja_JP.eucJP/articles/releng/"
remote-install = "ja_JP.eucJP/articles/remote-install/"
serial-uart = "ja_JP.eucJP/articles/serial-uart/"
solid-state = "ja_JP.eucJP/articles/solid-state/"
vinum = "ja_JP.eucJP/articles/vinum/"
vm-design = "ja_JP.eucJP/articles/vm-design/"

