title = "El Proyecto FreeBSD"
contentDir = "content/es"
languageName = "Spanish"
weight = 2

[books]
dev-model = "es_ES.ISO8859-1/books/dev-model/"
faq = "es_ES.ISO8859-1/books/faq/"
handbook = "es_ES.ISO8859-1/books/handbook/"
developers-handbook = "es_ES.ISO8859-1/books/developers-handbook/"
arch-handbook = "es_ES.ISO8859-1/books/arch-handbook/"
porters-handbook = "es_ES.ISO8859-1/books/porters-handbook/"
design-44bsd = "es_ES.ISO8859-1/books/design-44bsd/"
fdp-primer = "es_ES.ISO8859-1/books/fdp-primer/"

[articles]
bsdl-gpl = "es_ES.ISO8859-1/articles/bsdl-gpl/"
building-products = "es_ES.ISO8859-1/articles/building-products/"
committers-guide = "es_ES.ISO8859-1/articles/committers-guide/"
contributing = "es_ES.ISO8859-1/articles/contributing/"
contributors = "es_ES.ISO8859-1/articles/contributors/"
cups = "es_ES.ISO8859-1/articles/cups/"
explaining-bsd = "es_ES.ISO8859-1/articles/explaining-bsd/"
filtering-bridges = "es_ES.ISO8859-1/articles/filtering-bridges/"
fonts = "es_ES.ISO8859-1/articles/fonts/"
freebsd-questions = "es_ES.ISO8859-1/articles/freebsd-questions/"
freebsd-update-server = "es_ES.ISO8859-1/articles/freebsd-update-server/"
geom-class = "es_ES.ISO8859-1/articles/geom-class/"
gjournal-desktop = "es_ES.ISO8859-1/articles/gjournal-desktop/"
hubs = "es_ES.ISO8859-1/articles/hubs/"
ipsec-must = "es_ES.ISO8859-1/articles/ipsec-must/"
ldap-auth = "es_ES.ISO8859-1/articles/ldap-auth/"
leap-seconds = "es_ES.ISO8859-1/articles/leap-seconds/"
linux-emulation = "es_ES.ISO8859-1/articles/linux-emulation/"
linux-users = "es_ES.ISO8859-1/articles/linux-users/"
mailing-list-faq = "es_ES.ISO8859-1/articles/mailing-list-faq/"
nanobsd = "es_ES.ISO8859-1/articles/nanobsd/"
new-users = "es_ES.ISO8859-1/articles/new-users/"
pam = "es_ES.ISO8859-1/articles/pam/"
pgpkeys = "es_ES.ISO8859-1/articles/pgpkeys/"
port-mentor-guidelines = "es_ES.ISO8859-1/articles/port-mentor-guidelines/"
pr-guidelines = "es_ES.ISO8859-1/articles/pr-guidelines/"
problem-reports = "es_ES.ISO8859-1/articles/problem-reports/"
rc-scripting = "es_ES.ISO8859-1/articles/rc-scripting/"
releng = "es_ES.ISO8859-1/articles/releng/"
remote-install = "es_ES.ISO8859-1/articles/remote-install/"
serial-uart = "es_ES.ISO8859-1/articles/serial-uart/"
solid-state = "es_ES.ISO8859-1/articles/solid-state/"
vinum = "es_ES.ISO8859-1/articles/vinum/"
vm-design = "es_ES.ISO8859-1/articles/vm-design/"
