title = "The FreeBSD Project"
contentDir = "content/en"
languageName = "English"
weight = 1

[books]
dev-model = "doc/en_US.ISO8859-1/books/dev-model/"
faq = "doc/en_US.ISO8859-1/books/faq/"
handbook = "doc/en_US.ISO8859-1/books/handbook/"
developers-handbook = "doc/en_US.ISO8859-1/books/developers-handbook/"
arch-handbook = "doc/en_US.ISO8859-1/books/arch-handbook/"
porters-handbook = "doc/en_US.ISO8859-1/books/porters-handbook/"
design-44bsd = "doc/en_US.ISO8859-1/books/design-44bsd/"
fdp-primer = "doc/en_US.ISO8859-1/books/fdp-primer/"

[articles]
bsdl-gpl = "doc/en_US.ISO8859-1/articles/bsdl-gpl/"
building-products = "doc/en_US.ISO8859-1/articles/building-products/"
committers-guide = "doc/en_US.ISO8859-1/articles/committers-guide/"
contributing = "doc/en_US.ISO8859-1/articles/contributing/"
contributors = "doc/en_US.ISO8859-1/articles/contributors/"
cups = "doc/en_US.ISO8859-1/articles/cups/"
explaining-bsd = "doc/en_US.ISO8859-1/articles/explaining-bsd/"
filtering-bridges = "doc/en_US.ISO8859-1/articles/filtering-bridges/"
fonts = "doc/en_US.ISO8859-1/articles/fonts/"
freebsd-questions = "doc/en_US.ISO8859-1/articles/freebsd-questions/"
freebsd-update-server = "doc/en_US.ISO8859-1/articles/freebsd-update-server/"
geom-class = "doc/en_US.ISO8859-1/articles/geom-class/"
gjournal-desktop = "doc/en_US.ISO8859-1/articles/gjournal-desktop/"
hubs = "doc/en_US.ISO8859-1/articles/hubs/"
ipsec-must = "doc/en_US.ISO8859-1/articles/ipsec-must/"
ldap-auth = "doc/en_US.ISO8859-1/articles/ldap-auth/"
leap-seconds = "doc/en_US.ISO8859-1/articles/leap-seconds/"
linux-emulation = "doc/en_US.ISO8859-1/articles/linux-emulation/"
linux-users = "doc/en_US.ISO8859-1/articles/linux-users/"
mailing-list-faq = "doc/en_US.ISO8859-1/articles/mailing-list-faq/"
nanobsd = "doc/en_US.ISO8859-1/articles/nanobsd/"
new-users = "doc/en_US.ISO8859-1/articles/new-users/"
pam = "doc/en_US.ISO8859-1/articles/pam/"
pgpkeys = "doc/en_US.ISO8859-1/articles/pgpkeys/"
port-mentor-guidelines = "doc/en_US.ISO8859-1/articles/port-mentor-guidelines/"
pr-guidelines = "doc/en_US.ISO8859-1/articles/pr-guidelines/"
problem-reports = "doc/en_US.ISO8859-1/articles/problem-reports/"
rc-scripting = "doc/en_US.ISO8859-1/articles/rc-scripting/"
releng = "doc/en_US.ISO8859-1/articles/releng/"
freebsd-releng = "doc/en_US.ISO8859-1/articles/freebsd-releng/"
remote-install = "doc/en_US.ISO8859-1/articles/remote-install/"
serial-uart = "doc/en_US.ISO8859-1/articles/serial-uart/"
solid-state = "doc/en_US.ISO8859-1/articles/solid-state/"
vinum = "doc/en_US.ISO8859-1/articles/vinum/"
vm-design = "doc/en_US.ISO8859-1/articles/vm-design/"
