favicon = "images/favicon.ico"
styles = "fixed.css"
numports = "24.000"

[releases]
# Do not set this to 'INCLUDE' in this file.
betaLocalWhere = "IGNORE"
beta2LocalWhere = "IGNORE"

relHeadMajor = "13"
relHead = "13.0"

# If there is no release currently in the release cycle (i.e. we
# don't have something in BETAn or RCn), then change %beta.testing
# below to "IGNORE".  If we do, use "INCLUDE".

# Set to 'INCLUDE' when the schedule is available.
betaUpcoming = "INCLUDE"

# Set to 'INCLUDE' when the installation images are available
betaTesting = "INCLUDE"

betaRelCurrent = "11.4"
betaRelVers = "BETA2"
uBetaRelSchedule = "releases/11.4r/schedule/"

# If we have a second release in the release cycle (e.g. 5.x and 6.y
# are having release candidates at the same time), do the same here.

# Set to 'INCLUDE' when the schedule is available.
beta2Upcoming = "INCLUDE"

# Set to 'INCLUDE' when the installation images are available.
beta2Ttesting = "IGNORE"

betaRel2Current = "12.2"
betaRel2Vers = "RELEASE"
uBetaRel2Schedule = "releases/12.2r/schedule/"

# Release-specific macros to help keep other macros such as
# rel.current up-to-date without needing to do an entire tree
# sweep.  This allows switching rel.current, rel1.current, and
# rel2.current versions below with updated macros here, ultimately
# touching as few files as necessary.

# Note, this is a first pass at this structure, and by no means
# fully complete yet.  I plan to followup on this and expand it
# more (in addition to cleaning up this file) following the 11.3
# release (likely as part of the 11.3 announcement commit). -gjb

rel121CurrentMajor = "12"
rel121Current = "12.1"
rel121CurrentDate = "November, 2019"

# URLs to information on the latest release
uRel121Notes = "releases/12.1r/relnotes/"
uRel121Announce = "releases/12.1r/announce/"
uRel121Errata = "releases/12.1r/errata/"
uRel121Hardware = "releases/12.1r/hardware/"
uRel121Installation = "releases/12.1r/installation/"
uRel121Readme = "releases/12.1r/readme/"
uRel121Signatures = "releases/12.1r/signatures/"

rel120CurrentMajor = "12"
rel120Current = "12.0"
rel120CurrentDate = "December, 2018"

# URLs to information on the latest release
uRel120Notes = "releases/12.0r/relnotes/"
uRel120Announce = "releases/12.0r/announce/"
uRel120Errata = "releases/12.0r/errata/"
uRel120Hardware = "releases/12.0r/hardware/"
uRel120Installation = "releases/12.0r/installation/"
uRel120Readme = "releases/12.0r/readme/"
uRel120Signatures = "releases/12.0r/signatures/"

rel113CurrentMajor = "11"
rel113Current = "11.3"
rel113CurrentDate = "July, 2019"

# URLs to information on the latest release
uRel113Notes = "releases/11.3r/relnotes/"
uRel113Announce = "releases/11.3r/announce/"
uRel113Errata = "releases/11.3r/errata/"
uRel113Hardware = "releases/11.3r/hardware/"
uRel113Installation = "releases/11.3r/installation/"
uRel113Readme = "releases/11.3r/readme/"
uRel113Signatures = "releases/11.3r/signatures/"

rel112CurrentMajor = "11"
rel112Current = "11.2"
rel112CurrentDate = "June, 2018"

# URLs to information on the latest release
uRel112Notes = "releases/11.2r/relnotes/"
uRel112Announce = "releases/11.2r/announce/"
uRel112Errata = "releases/11.2r/errata/"
uRel112Hardware = "releases/11.2r/hardware/"
uRel112Installation = "releases/11.2r/installation/"
uRel112Readme = "releases/11.2r/readme/"
uRel112Signatures = "releases/11.2r/signatures/"

# URLs for backwards compatibility with previous doc structure
relCurrentMajor = "12"
relCurrent = "12.0"
relCurrentDate = "December, 2018"

# URLs to information on the latest release
uRelNotes = "releases/12.0r/relnotes/"
uRelAnnounce = "releases/12.0r/announce/"
uRelErrata = "releases/12.0r/errata/"
uRelHardware = "releases/12.0r/hardware/"
uRelInstallation = "releases/12.0r/installation/"
uRelReadme = "releases/12.0r/readme/"
uRelSignatures = "releases/12.0r/signatures/"

rel1CurrentMajor = "11"
rel1Current = "11.3"
rel1CurrentDate = "July, 2019"

# URLs to information on the latest release
uRel1Notes = "releases/11.3r/relnotes/"
uRel1Announce = "releases/11.3r/announce/"
uRel1Errata = "releases/11.3r/errata/"
uRel1Hardware = "releases/11.3r/hardware/"
uRel1Installation = "releases/11.3r/installation/"
uRel1Readme = "releases/11.3r/readme/"
uRel1Signatures = "releases/11.3r/signatures/"

rel2CurrentMajor = "11"
rel2Current = "11.2"
rel2CurrentDate = "June, 2018"

# URLs to information on the latest release
uRel2Notes = "releases/11.2r/relnotes/"
uRel2Announce = "releases/11.2r/announce/"
uRel2Errata = "releases/11.2r/errata/"
uRel2Hardware = "releases/11.2r/hardware/"
uRel2Installation = "releases/11.2r/installation/"
uRel2Readme = "releases/11.2r/readme/"
uRel2Signatures = "releases/11.2r/signatures/"

# URLs to old releases, kept so the build succeeds

# Tertiary "current release" entities
rel3CurrentMajor = "10"
rel3Current = "10.2"
rel3CurrentDate = "August, 2015"

# URLs to information on the latest release
uRel3Notes = "releases/10.2r/relnotes/"
uRel3Announce = "releases/10.2r/announce/"
uRel3Errata = "releases/10.2r/errata/"
uRel3Hardware = "releases/10.2r/hardware/"
uRel3Installation = "releases/10.2r/installation/"
uRel3Readme = "releases/10.2r/readme/"
uRel3Signatures = "releases/10.2r/signatures/"

# Gnome
gnomeoldver = "2.30"
gnomever = "2.32"
gnomedevelver = "3.6"
