---
title: "FreeBSD Documentation Project: Documentation Set"
sidenav: docs
--- 

= FreeBSD Documentation Project: Documentation Set

The project is a fairly loosely knit group of people, and the only thing we have in common is that we are subscribed to the mailing list FreeBSD-doc@FreeBSD.org.

Some of us can commit changes directly to the FreeBSD documentation tree. There is a complete list of {{< articles "contributors" "all FreeBSD developers with commit privileges" "staff-committers.html" >}}, as well as a list of the link:../../administration/#t-doceng[principal committers for the FreeBSD Documentation Project].

Others do not have commit privileges, but write and submit documentation nonetheless. Once the documentation has been submitted according to the link:../submitting[Submit Documentation] page, one of the committers will then review it and include it in the documentation set.

To help with the documentation project (and we fervently hope you do), just subscribe to the mailing list and participate. As soon as you have done that, you're a member of the project.

link:../[FreeBSD Documentation Project Home]
