---
title: Εγχειρίδιο του FreeBSD
authors:
  - author: Ομάδα Τεκμηρίωσης του FreeBSD
copyright: 1995-2020 Ομάδα Τεκμηρίωσης του FreeBSD
releaseinfo: "$FreeBSD: head/el_GR.ISO8859-7/books/handbook/book.xml 43641 2014-01-25 10:27:24Z manolis $" 
trademarks: ["freebsd", "ibm", "ieee", "redhat", "3com", "adobe", "apple", "intel", "linux", "microsoft", "opengroup", "sun", "realnetworks", "oracle", "3ware", "arm", "adaptec", "heidelberger", "intuit", "lsilogic", "themathworks", "thomson", "vmware", "wolframresearch", "xiph", "xfree86", "general"] 
---

= Εγχειρίδιο του FreeBSD
:doctype: book
:toc: macro
:toclevels: 2
:icons: font
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnums:
:partnums:
:chapter-signifier: Chapter
:part-signifier: Part
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:figure-caption: Figure
:book: True
:pgpkeys-path: ../../../../../

ifeval::["{backend}" == "html5"]
include::share/mirrors.adoc[]
include::share/authors.adoc[]
include::share/releases.adoc[]
include::share/gr/mailing-lists.adoc[]
include::share/gr/teams.adoc[]
include::share/gr/urls.adoc[]
:chapters-path: content/gr/books/handbook/
endif::[]

ifeval::["{backend}" == "pdf"]
include::../../../../share/mirrors.adoc[]
include::../../../../share/authors.adoc[]
include::../../../../share/releases.adoc[]
include::../../../../share/gr/mailing-lists.adoc[]
include::../../../../share/gr/teams.adoc[]
include::../../../../share/gr/urls.adoc[]
:chapters-path:
endif::[]

ifeval::["{backend}" == "epub3"]
include::../../../../share/mirrors.adoc[]
include::../../../../share/authors.adoc[]
include::../../../../share/releases.adoc[]
include::../../../../share/gr/mailing-lists.adoc[]
include::../../../../share/gr/teams.adoc[]
include::../../../../share/gr/urls.adoc[]
:chapters-path:
endif::[]

[.abstract-title]
Περίληψη

Καλώς ήρθατε στο FreeBSD! Αυτό το εγχειρίδιο καλύπτει την εγκατάσταση και την καθημερινή χρήση του _FreeBSD {rel112-current}-RELEASE_ και του _FreeBSD {rel.current}-RELEASE_. Το βιβλίο αυτό είναι _μόνιμα υπό βελτίωση και ανάπτυξη_ και αποτελεί το αποτέλεσμα της δουλειάς πολλών ατόμων, οπότε κάποια τμήματα μπορεί να περιέχουν σχετικά ξεπερασμένες πληροφορίες και να χρειάζονται ανανέωση. Αν ενδιαφέρεστε να μας βοηθήσετε σε αυτό το έργο, επικοινωνήστε μαζί μας στην {freebsd-doc}. Η τελευταία έκδοση αυτού του κειμένου είναι πάντα διαθέσιμη από την http://www.FreeBSD.org/[ιστοσελίδα του FreeBSD] (παλιότερες εκδόσεις μπορείτε να βρείτε στη διεύθυνση http://docs.FreeBSD.org/doc/[http://docs.FreeBSD.org/doc/]). Μπορείτε επίσης να μεταφορτώσετε στον υπολογιστή σας το ίδιο βιβλίο σε άλλες μορφές αρχείου και με διάφορες μορφές συμπίεσης από τον link:ftp://ftp.FreeBSD.org/pub/FreeBSD/doc/[εξυπηρετητή FTP του FreeBSD] ή ένα από τα πολλά <<mirrors-ftp,mirror sites>>. Αν προτιμάτε ένα τυπωμένο αντίτυπο, μπορείτε να αγοράσετε ένα αντίγραφο του Εγχειριδίου, από το http://www.freebsdmall.com/[FreeBSD Mall]. Μπορείτε επίσης να link:https://www.FreeBSD.org/search/[ψάξετε σε όλο το βιβλίο].

'''

include::content/en/books/handbook/toc.adoc[]
